### ISSUE TITLE
[BUG] - No Longer getting trade msg popups on incoming/outgoing messages

### ISSUE THREAD

**Issue by indeed317** [Morph21/MercuryTrade-Community-Fork#160]
new ver - zero incoming/outgoing popups anymore nor does it make the infamous merc trade noise.  This was working fine before the 3.23 PoE patch.  I've checked its using the correct game dir path...restarted...nothing seems to work.

any quick ideas?  i trade for a huge group and im going to be struggling if i can't figure this out.

thanks <3

**Comment by TactfulRanger** [comment]
Same problem here. None of the well-known trade tools seem to be working. Something must have changes to chatlogs i guess?

**Comment by indeed317** [comment]
I updated java/c++ redistro...tried 3 other 3rd party trade apps and they're all borked.  Odd bc i checked the client.txt and the location isn't changed and its still logging as normal.  this is where my brain stops and i hope someone smarted than I can maybe figure out the issue.

**Comment by TactfulRanger** [comment]
If that's true, the only reason could be that the formatting inside the client.txt has changed.

**Comment by indeed317** [comment]
had the first pop up...and couldn't invite him with the button "character does not exist"  you can see the name fully in the chat window below where merc trade didnt have the first letter.  lol yeah so def something with the formatting attached is the screen shot

![image](https://github.com/Morph21/MercuryTrade-Community-Fork/assets/56525274/c9de72b6-45ea-4554-87a5-e798a751da20)

**Comment by Legushka26** [comment]
Same issue. 3.23 broke MercuryTrade.

**Comment by indeed317** [comment]
Just posting again another screen shot of only the 2nd msg i've had pop up and again the character started with DE and it was pruned - maybe this will help the dev working on the solution 
![image](https://github.com/Morph21/MercuryTrade-Community-Fork/assets/56525274/27976f2f-e65f-41db-9166-2bfa1b7c72d1)

**Comment by indeed317** [comment]
for context im trading for snap/empys group and im trading NON STOP as you can see in the window lol.  so far only 2 of the trade boxes have worked...both similar naming conventions at the start

**Comment by indeed317** [comment]
And again...this will be my last screen shot but these naming conventions are very similar
![image](https://github.com/Morph21/MercuryTrade-Community-Fork/assets/56525274/9403ba13-b90e-4ff2-98c9-27ceb87d42df)

**Comment by MarkuszPoE** [comment]
It looks like this is caused by GGG changing logged whispers to not include @From or @To any more, I submitted a bug report 
https://www.pathofexile.com/forum/view-thread/3453447

It may be temporarily fixed if you remove language specific LocalizationMatchers in TradeIncMessagesInterceptor.java

**Comment by Morph21** [comment]
Can you confirm that this issue was fixed? I kinda just get up to see 10 messages on one bug :D

**Comment by Ham5terzilla** [comment]
still doesn't work for me. :(
Working for outgoing, but not for ingoing.

**Comment by TactfulRanger** [comment]
It seems to have stopped working for me as well as of today.

**Comment by Legushka26** [comment]
For some reason, the tool works perfectly fine for me in Standard, but doesn't work at all in Affliction

**Comment by Morph21** [comment]
seems like it's working now, probably ggg messed up with format messages they log in their file
